### ISSUE TITLE
Add Changelogs

### ISSUE THREAD

**Issue by aatauil** [appuniversum/ember-appuniversum#105]
To ease upgrading appuniversum in our apps it would be very helpfull to have a changes history (changelog) so we can quickly spot the potentially breaking changes before upgrading our app. Another alternative is to specify the changes made in the release notes or description (in github) of a new release or tag  :) 

Let me know what you think

**Comment by Windvis** [comment]
https://github.com/appuniversum/ember-appuniversum/issues/81#issuecomment-823861337

If `release-it` is setup using [create-rwjblue-release-it-setup](https://github.com/rwjblue/create-rwjblue-release-it-setup), it will include release-it-lerna-changelog which can generate changelogs based on PR labels and titles which is very nice.

**Comment by Dietr** [comment]
Feel free to implement something like this. For now I'm adding notes in the Github releases.
