### ISSUE TITLE
links styled as buttons

### ISSUE THREAD

**Issue by Windvis** [appuniversum/ember-appuniversum#110]
The `<AuButton>` component can already be made to look like a link by using the `tertiary` skin. The reverse however is not yet possible without adding css classes manually.

Since styling links as buttons is very common and using buttons + JavaScript for redirecting isn't great for a11y, I think it would make sense to cover this use-case in the addon.

Maybe a dedicated `<AuButtonLink>` + primary / secondary skins? Or maybe extra skin types for the `<AuLink>` component (`button-primary` / `button-secondary`)?

Thoughts?

**Comment by nvdk** [comment]
I think the skin type makes most sense ?

**Comment by Windvis** [comment]
Closed by #112
