### ISSUE TITLE
Date input component

### ISSUE THREAD

**Issue by Windvis** [appuniversum/ember-appuniversum#119]
The `<AuDatePicker>` component isn't always the most user friendly solution for dates. Dates far in the future / past are not easy to select at the moment. A better alternative for those use cases might be a "simple" date input component. Something that formats the users input in the expected format maybe?

**Comment by Windvis** [comment]
The input field kind of works like this already. The user can type the date in the correct format and it will select the right one. It doesn't use input masks though so it's still not the best UX.

**Comment by Windvis** [comment]
It seems splitting a date in separate input fields is the most user friendly solution for a date of birth field according to the following article (which links to sources to back up that claim):

https://blog.prototypr.io/best-practice-for-date-of-birth-form-fields-91bf67bb3640

I guess we want an appuniversum version of the GOV.UK's [Date input component](https://design-system.service.gov.uk/components/date-input/).

**Comment by Windvis** [comment]
It seems that Webuniversum uses a masking library for this: https://overheid.vlaanderen.be/webuniversum/v3/documentation/forms/vl-ui-pattern

Creating an Ember version of the masking library they use could also be an option.

**Comment by mietcls** [comment]
Agreed that we could use the simple form, without a picker – I see people struggle with it often during user tests as well (with good and bad date pickers).

- separate date fields will also increase clicks; and our clients have to put in dates quite often. They are usually not "power users" that will use the tab, but they will click on everything (for instance hitting "enter" after a search also doesn't happen often). So these are not one-off patterns like for gov.uk, but daily usage – sometimes multiple times a day. Gov.uk does excellent research though – but we would need to test the pattern in our context and probably revisit (you can put multiple numbers in one field, more than allowed, when you've finished one dat it does not jump to the next field, which would sometimes be useful but can also be a drag, ... there's a lot to consider here). I also recently read an article that fights this pattern – if I find it I will link it. 
- the webuniversum style: The masking is very nice. However they use a pattern where they already show placeholder text which decreases accessibility for visually impaired people and people with reduced cognitive abilities. But the simplicity is nice.
- Loket: here's also a "masking" pattern here that gives a visual hint about how to fill out certain fields, without the danger of _seeming_ to be filled out already (could be better though, more subtle like the one from webuniversum). Try "voeg mandataris toe" and then "voeg iemand buiten de lijst toe":
<img width="161" alt="Screenshot 2021-09-23 at 09 34 09" src="https://user-images.githubusercontent.com/1572885/134470002-91cb84ad-9f6c-4b8b-bd0c-7cd0beab9157.png"> 

Unfortunately it only appears when you hover/click it, before it still shows this:
<img width="171" alt="Screenshot 2021-09-23 at 09 34 32" src="https://user-images.githubusercontent.com/1572885/134470039-f6a7f8f6-c3be-4e35-92e2-5f9d5217ba8e.png">

A combination of the webuniversum style, with (when applicable) extra visual hints or help text could be a step forward indeed.

**Comment by Windvis** [comment]
Blocked by #201

**Comment by nbittich** [comment]
Another workaround to select  a date in the past / restrict dates in the future is to use 
```
      @min={{this.min}}
      @max={{this.max}}
``

**Comment by nbittich** [comment]
FYI we implemented something like this in OP:

https://user-images.githubusercontent.com/3816305/171859750-5f9b7adb-40b4-4adc-aee7-682f464130e8.mp4
