### ISSUE TITLE
Missing dependency when installing `ember-appuniversum`

### ISSUE THREAD

**Issue by BT-Creator** [appuniversum/ember-appuniversum#123]
When installing `ember-appuniversum` with the ember-cli, the secondary dependency, [`appuniversum`](https://www.npmjs.com/package/@appuniversum/appuniversum) is not installed, which causes that the app cannot be served, because the SCSS files are missing.

***Temporary Fix:** After installing `ember-appuniversum`, manually install appuniversum using `npm i @appuniversum/appuniversum`, this should fix the problem*

You can find the version of the `ember-cli` and `node` used below:
- `ember-cli`: 3.27.0
- `node`: 14.15.1

**Comment by Windvis** [comment]
When I tried the app locally, the dependency _was_ installed, just not in the top level node_modules folder. Instead it was installed in the `node_modules/@appuniversum/ember-appuniversum/node_modules/@appuniversum/appuniversum`.

This should normally only happen when the dependency isn't deduped and multiple versions are in play (which wasn't the case).

Something fishy is going on that's for sure, but I don't think it's fixable in this addon itself.

Maybe documenting the issue in the setup guides might be enough for now?
