### ISSUE TITLE
Include ACM/IDM components

### ISSUE THREAD

**Issue by Windvis** [appuniversum/ember-appuniversum#142]
The styled components in the [`@lblod/ember-acmidm-login`](https://github.com/lblod/ember-acmidm-login) addon are [being deprecated](https://github.com/lblod/ember-acmidm-login/pull/6). Instead the addon will focus only on the login logic itself, and not the presentation of that logic.

Since most apps still need these components I think it makes sense to house them in this addon instead. This will be similar to the file-upload component that was added recently.

Most projects also include a custom AcmidmLoginCompact button which is used in the main header of the app which requires custom css to make the error message display properly. That component could also be moved here.

Not every project will require this functionality, but since the components themselves won't be that huge, and the styles can simply not be imported, I think the ease of maintenance will be worth the possible downsides.

The acmidm-login addon itself can be listed as a peerDependency or optionalDependency and only be installed in the projects that need it.

**Comment by Dietr** [comment]
Good idea. This would also simplify the css we now use for this.

**Comment by claire-lovisa** [comment]
I've noticed that when upgrading apps to ember v3.28 we have a warning because of the version of `ember-cli-babel` used in `torii`, :+1: to the new component if it can improves this as well !

**Comment by Windvis** [comment]
Closing since we don't need the components anymore in future ember-acmidm-login versions: https://github.com/lblod/ember-acmidm-login/pull/14
