### ISSUE TITLE
0.6.4 AuButtonGroup styling regression

### ISSUE THREAD

**Issue by Windvis** [appuniversum/ember-appuniversum#156]
It seems [some recent style changes](
https://github.com/appuniversum/ember-appuniversum/commit/8327eb29e0b76429837bf62f98d5efb78b0dd0df#diff-ec0c1f18b19b2d1a29ad53616771af79795f9f7e692d109d902d926c823c066aR6-R25) cause whitespace issues.

Before (0.6.3):
![image](https://user-images.githubusercontent.com/3533236/141480040-d2101b04-0c8d-4e0f-8a3d-df2971536f9e.png)

After updating to 0.6.4:
![image](https://user-images.githubusercontent.com/3533236/141479962-367eb80b-5016-4503-a763-7e97eb63e2fa.png)

It seems the [docs website](https://appuniversum.github.io/ember-appuniversum/docs/atoms/au-button-group) contains whitespace between buttons which is why it's not noticeably there:
![image](https://user-images.githubusercontent.com/3533236/141480352-4dd392f3-d701-4424-a081-015f761f6b95.png)

**Comment by Windvis** [comment]
@Dietr It seems there was an other regression / breaking change that I didn't notice last time. Due to the au-c-button-group now having a margin-top value, it can't be used as a direct child of `.au-o-flow`.

We're using `.au-o-flow` to space out elements consistently but now the AuButtonGroup overrides that whitespace:
![image](https://user-images.githubusercontent.com/3533236/142387866-ecb30cbc-38d0-4a5a-b6bf-3adafd79e5a4.png)

We could add wrapper divs but I would rather not do that since it's confusing when reading the code why that div is needed in the first place.

Are we using au-o-flow incorrectly or was this an oversight when implementing these changes?

**Comment by Dietr** [comment]
@Windvis This is indeed a conflict between the button-group and the au-o-flow object. Will look into it.

**Comment by Dietr** [comment]
Should be fixed in 0.6.6. Used the gap property to simplify the code and avoid the margin conflict.

**Comment by Windvis** [comment]
@Dietr thanks for fixing it so fast!
