### ISSUE TITLE
A lot of linter errors

### ISSUE THREAD

**Issue by Wolfr** [appuniversum/ember-appuniversum#16]
If I run the project I get 150+ lines of linter errors.

https://gist.github.com/Wolfr/e5d3b5b07431314396f2ce137d53c627

I am not knowledgeable enough in Ember to fix this, but just noting this as a problem.

**Comment by Dietr** [comment]
This is due to the mix of syntax (Ember octane vs old ember). The addon-docs plugin is not written in octane so the cli gives these linter errors. I'm aware that this needs fixing but it's quite some work to convert this addon.

**Comment by Wolfr** [comment]
Just mentioning. The project we have also comes with a bunch of linter errors. This seems to be an Ember thing ;)
