### ISSUE TITLE
ember-auto-import v2 update was a breaking change

### ISSUE THREAD

**Issue by Windvis** [appuniversum/ember-appuniversum#161]
It seems that ember-auto-import was recently updated to version 2. This is a breaking change since the addon can now only be used in apps that have v2 installed as well. 

Updating our apps to ember-auto-import v2 shouldn't be a major problem but I'm pretty sure not many apps will be using it at the moment. So that might cause issues if they update to the latest version of ember-appuniversum before doing the ember-auto-import update.

I also noticed that webpack was installed as a dependency as well, while the [upgrade guide](https://github.com/ef4/ember-auto-import/blob/main/docs/upgrade-guide-2.0.md) says that it's not something addons should do.

Was there a specific reason the version needed to be bumped? I know it's a requirement for v4 apps but I don't think any of our apps are v4 yet?

Some relevant snippets from the ember-auto-import upgrade guide:
> addons that upgrade to ember-auto-import >= 2 will only work in apps that have ember-auto-import >= 2, so they should do their own semver major releases when they upgrade

> Addons that use ember-auto-import 2.0 should not put webpack into dependencies (the app's version will be used instead). They will need it in devDependencies in order to build their own dummy app.

**Comment by Dietr** [comment]
Ok, thanks for the info. Was not aware that this was a breaking change (my bad, didn't read the docs). I updated this dependency because my build was complaining. Not sure what changed.

What's the best way forward with this? Move webpack to devDependencies or find a way to downgrade the auto-import package?

**Comment by Windvis** [comment]
Sorry, forgot to answer. I think we can just double down and require ember-auto-import v2? Ember 4 requires that version as well so it eventually needs to happen for the active projects anyway. Apps that can't update for some reason probably won't be using the latest version of ember-appuniversum either.

We do probably need to follow the recommendation of moving webpack to devDeps though. And maybe update the compatibility guide as well?
