### ISSUE TITLE
`AuButtonGroup` alignment options

### ISSUE THREAD

**Issue by Windvis** [appuniversum/ember-appuniversum#162]
The `<AuButtonGroup>` component is great to add consistent white space between buttons. However, sometimes the button group needs to be displayed on the right side of a page and the current implementation always aligns the buttons on the left side. This can look a bit weird in practice:

![image](https://user-images.githubusercontent.com/3533236/145999775-ea24b336-638b-4d12-afa4-8fae238a334e.png)

An argument to override the default alignment would be nice. Alternatively adding more [flex alignment based utils](https://tailwindcss.com/docs/justify-content) could also solve the problem in a more generic way. 

In our case we only want this alignment from a certain breakpoint, so a standalone class with breakpoint versions might be better?

**Comment by Dietr** [comment]
Adding some flex based alignment utilities similar to https://appuniversum.github.io/appuniversum/utilities/align-text/ will probably be the most flexible.
