### ISSUE TITLE
Warning states for labels, inputs and help texts

### ISSUE THREAD

**Issue by Windvis** [appuniversum/ember-appuniversum#163]
In our app we have multiple inputs that could potentially affect other inputs. For example, clearing a value from a certain select should also clear a value in a different select. This works, but it might be confusing since there is no explanation why the second value was cleared. We were thinking that adding a warning state to the second select which explains the reason why it was cleared might be a more user friendly alternative. It would look similar to the error state, but with a different icon and coloring.

Is this a good idea or are there better alternatives?

**Comment by Dietr** [comment]
Seems like a good idea. We can sync this with the warning label/color we use on the alert component.
