### ISSUE TITLE
AuDatePicker seems broken in the 0.7.1+ docs

### ISSUE THREAD

**Issue by Windvis** [appuniversum/ember-appuniversum#164]
https://appuniversum.github.io/ember-appuniversum/docs/atoms/au-form-datepicker

The console shows the following error:
```
Uncaught (in promise) ChunkLoadError: Loading chunk 410 failed.
(error: https://appuniversum.github.io/ember-appuniversum/docs/atoms/ADDON_DOCS_ROOT_URL/assets/chunk.410.8346a36c9382a21427e3.js)
    Ember 38
chunk.143.3dbc28093b5449ba0947.js:25:20
```
I haven't tested the 0.7.2 release in a project yet, so not sure if it is a docs only problem.

**Comment by Dietr** [comment]
Seems to be a docs or deploy problem. Won't put much effort in to it as we're working towards replacing these docs with storybook.
