### ISSUE TITLE
Button documentation

### ISSUE THREAD

**Issue by Wolfr** [appuniversum/ember-appuniversum#17]
* [ ] Button with icon
* [ ] Icon only button
* Have discussion around ghost vs secondary button

**Comment by Wolfr** [comment]
I am thinking that we need more buttons docs if we are to switch over to the set of components you are working on at some point in time. The button page is definitely not “feature complete” yet. I will also discuss in our team how we can contribute.

**Comment by Dietr** [comment]
I'm currently working on this. You can see some progress in https://github.com/appuniversum/ember-appuniversum/tree/feature/buttons
