### ISSUE TITLE
`au-c-content--tiny` modifier

### ISSUE THREAD

**Issue by Windvis** [appuniversum/ember-appuniversum#179]
In https://github.com/lblod/frontend-loket/pull/66 we added a custom `au-c-content--tiny` modifier since it makes the content look like "help text" which is what we need there.

Should we add that modifier to ember-appuniversum as well or is the case not generic enough to warrant it? An alternative could be that we add support for adding "content" in the help text component itself.

**Comment by Dietr** [comment]
I prefer adding the `au-c-content--tiny` modifier.
