### ISSUE TITLE
Popover vs dropdown: needs to be fixed in docs

### ISSUE THREAD

**Issue by Wolfr** [appuniversum/ember-appuniversum#18]
In the current development branch, there is a page which mentions a popover, but then shows a dropdown.

We already had a discussion about the naming of the popover vs dropdown, just putting it here that this current implementation is not following the outcome of that discussion yet.

In general we need to take a clear look at the names of things when talking about things that are similar but not the same e.g. menu vs popover vs dropdown vs nav menu vs select.

![image](https://user-images.githubusercontent.com/12690/78971521-0f048580-7b0c-11ea-970e-a4e540e6fab4.png)

**Comment by Dietr** [comment]
See #15

**Comment by Wolfr** [comment]
Right, sorry, just unclear with the many branches where to look.
