### ISSUE TITLE
New scss files that group imports

### ISSUE THREAD

**Issue by Windvis** [appuniversum/ember-appuniversum#194]
The current docs lists 2 options for importing the scss:

1. a single import which imports everything: `@import "ember-appuniversum";` which has the benefit that the addon decides what goes in the build, but apps don't have control over the order.
2. List all the imports in the app. This provides the most control but requires manual maintenance of the imports when updating

There is a middle ground between these 2 options that might be worth it. We could create scss files for each "type" of import. Projects can then import these files if they need more control than option 1, but still want to import all the styles from appuniversum.

This is what it could look like if you create a file for each "title" in the huge import list, but there might be better ways to group things.
```scss
@import "ember-appuniversum/variables";
@import "ember-appuniversum/mixins";
@import "ember-appuniversum/generic";
@import "ember-appuniversum/elements";
@import "ember-appuniversum/objects";
@import "ember-appuniversum/components";
@import "ember-appuniversum/plugins";
@import "ember-appuniversum/utilities";
```

Apps can then add new app specific styles in the correct place.

**Comment by Windvis** [comment]
The loket app would benefit from this since it still depends [on other styles and components](https://github.com/lblod/frontend-loket/blob/development/app/styles/app.scss#L56-L61), and replacing the appuniversum styles with a single import changes the order of the classes which might affect the app and issues would be hard to detect.

**Comment by Dietr** [comment]
Good idea, i did something similar for the rdfa-editor and this could also improve that implementation. Seems pretty easy to implement.
