### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by Windvis** [appuniversum/ember-appuniversum#196]
Multiple projects have been using this addon for a long time now. I would release the project as 1.0 so dependency maintenance is easier. The 0 major release is only intended for early development which is why every minor can contain breaking changes and why npm can't deduplicate multiple minor versions in your node_modules tree. 

If addons can depend on `^1.0.0` npm can simply install the version that the host app defines and addons won't have to be updated until a new major is released.

**Comment by Dietr** [comment]
Latest released was 1.0.0
