### ISSUE TITLE
Aria hidden

### ISSUE THREAD

**Issue by Wolfr** [appuniversum/ember-appuniversum#2]
https://github.com/appuniversum/ember-appuniversum/blob/426d8865bad0f3783ca7f690a0a16d430193b028/addon/components/au-header.hbs#L5

Why aria-hidden="true" on this image?

**Comment by Dietr** [comment]
I did not see the necessity to have a screenreader read out "Logo Vlaanderen" followed by "Vlaanderen". I could be wrong of course.
