### ISSUE TITLE
Small button variant

### ISSUE THREAD

**Issue by Windvis** [appuniversum/ember-appuniversum#211]
It seems webuniversum ships with a small variant of the button components, for example:

![image](https://user-images.githubusercontent.com/3533236/155989308-fed01ee6-968b-4428-9eb2-f557fffcc903.png)

Is this something that should be added to Appuniversum as well, or should it be replaced with a different pattern instead?

**Comment by Dietr** [comment]
I think the small button is a deprecated webuniversum component. But maybe our default button is too large. Ideally we should follow the new styles:

![Screenshot 2022-03-03 at 10 50 46](https://user-images.githubusercontent.com/2385322/156540155-c601234c-f0b2-408c-8d89-6a9bcc87ec3f.png)
