### ISSUE TITLE
`IconList` component

### ISSUE THREAD

**Issue by Windvis** [appuniversum/ember-appuniversum#212]
I noticed an [`<IconList>` component](https://github.com/appuniversum/ember-appuniversum/blob/development/addon/components/au-icon-list.hbs) was added recently. Is this something that's actually used in applications? If it's only for the storybook docs I think we can move it to the dummy app so that it doesn't get bundled in all consuming applications.

**Comment by Dietr** [comment]
Yes, I should have added this to the dummy app. This is only used in the storybook docs.
