### ISSUE TITLE
Visual bugs in the 1.4 release

### ISSUE THREAD

**Issue by Windvis** [appuniversum/ember-appuniversum#314]
**Describe the bug**
It seems that the 1.4 release causes some issues in the Loket app:

- The sidebar no longer fills the whole height
- buttons which should be positioned at the bottom no longer do
- Some dropdowns are cut off if they are longer than the content
- probably more subtle things

The most likely cause is #311 

Loket is an old app so it is still using css classes instead of the newer container components which might be the cause. Replacing those in all modules isn't a quick job and not high priority either since everything worked and the css classes are still supported (I assume?).

I did try to wrap the app in the `AuApp` component and that does fix the sidebar, but not the other issues (and it introduces new ones).

**To Reproduce**
1. Go to https://loket.lblod.info
2. log in as a user which can access most modules (Gemeente)
3. Click around the interface

https://dev.loket.lblod.info still uses an older version so that version can be compared to see how it's supposed to look.

**Expected behavior**
Everything looks as expected

**Screenshots**
![image](https://user-images.githubusercontent.com/3533236/186616904-8573430e-93a8-4360-b041-c82165fb68e6.png)

![image](https://user-images.githubusercontent.com/3533236/186616800-b106c611-4578-457b-b0c5-b8e9eff1c938.png)

![image](https://user-images.githubusercontent.com/3533236/186616301-4f9a7662-1a4e-48ab-aa7e-c6b31b9a04fd.png)

**Desktop (please complete the following information):**
 - Browser: Firefox, Chrome

**Comment by Windvis** [comment]
I have a [WIP PR](https://github.com/lblod/frontend-loket/pull/172) which fixes some things, but the removal of the flex styles of the body container seems to cause issues. 

Should we start using flex utils instead?

**Comment by Dietr** [comment]
I created a fix for the body container https://github.com/appuniversum/ember-appuniversum/pull/315. I have no fix for not using the AuApp container component. It's necessary to allow correct spacing in other applications. Did a quick test on loket and it seems to fix the layout issues you describe (with adding the AuApp component).

**Comment by Windvis** [comment]
Hmm, I'm afraid a lot of apps don't have that `AuApp` wrapper yet and since most don't use a lock file they might run into this issue while deploying, as we did in Loket 😄. It wasn't a "requirement" before right?

Would it make sense to revert it and expose it as an optional css file that apps can import? We could then make it the default in the v2 release? Maybe we could even add some way to detect if the AuApp component is used and throw a warning if it's not (and an error in v2).

**Comment by Dietr** [comment]
Ok, will have a look on making the AuApp component optional so it's compatible with older versions and also supports apps that do use it.

**Comment by Dietr** [comment]
Updated #315: tested on Loket and GN. Both options (with or without AuApp component) work now.

**Comment by Windvis** [comment]
Closed by #315
