### ISSUE TITLE
Addition of skins & manual dividers for dropdown component

### ISSUE THREAD

**Issue by brenner-company** [appuniversum/ember-appuniversum#317]
**The addition of the following features for the dropdown component:**
- possibility of using a skin on the dropdown trigger button (such as defined in the button component).
- possibility of disabling the automatic dividers so that a manual structure can be defined.

---

**Possibility of using a skin on the dropdown trigger button (such as defined in the button component):**

Inside the Kaleidos app, we use a dropdown menu on a few different types of button. Adding the same kind of skins (at least `primary`, `secondary` & `naked`) as used inside the button component would provide a solution to this need.

Example of current use within Kaleidos:

<img width="243" alt="CleanShot 2022-09-08 at 13 11 16@2x" src="https://user-images.githubusercontent.com/18174827/189107923-2b7637aa-dd18-4b29-996e-d753242a8d4f.png">

---

**Possibility of disabling the automatic dividers so that a manual structure can be defined:**

Inside the Kaleidos app, we don't use automatic dividers between menu items. When needed, we can add manual dividers to create structure within the menu list. With the added option of disabling automatic dividers we could also add the same structure ourselves with the use of, for example, `AuHr` components.

Example of current use within Kaleidos:

<img width="275" alt="CleanShot 2022-09-08 at 13 30 44@2x" src="https://user-images.githubusercontent.com/18174827/189111539-c48dca47-afa0-40ae-8ee5-826e0b4db215.png">

---

The first feature is rather a must-have, the second one is a nice-to-have.

**Comment by Dietr** [comment]
I think this is a good addition for other products. Already started on this as there's some other changes that need to be done on the dropdown. Will create a PR this week to show how we can combine both styles.

**Comment by brenner-company** [comment]
> I think this is a good addition for other products. Already started on this as there's some other changes that need to be done on the dropdown. Will create a PR this week to show how we can combine both styles.

Thanks!

If it's ok with you, I also have a few minor styling tweaks at the ready. Can I add them to the future PR?
