### ISSUE TITLE
Additional skins for external link component

### ISSUE THREAD

**Issue by brenner-company** [appuniversum/ember-appuniversum#339]
Within Kaleidos we need to a few links for downloading files that are styled as naked buttons (for example, as used for the [regular link component](https://appuniversum.github.io/ember-appuniversum/?path=/story/components-links-aulink--naked-button&args=icon:download;hideText:true)). Because the regular link component is a `LinkTo` it doesn't accept `download` attributes and we can't use it in this case.

Can I add the 3 (missing) `button-` skins (`button`, `button-secondary` & `button-naked`) to the `AuLinkExternal` component?

This FR is rather urgent because it is a bug release for Kaleidos will be waiting on this.

**Comment by Windvis** [comment]
We could also use this for Digitaal Loket. I noticed we've been using regular `a` tags with the needed classes in some places so this would be a good replacement for that 👍.

**Comment by Windvis** [comment]
Closed by #340
