### ISSUE TITLE
Addition of sub- & superscript icons

### ISSUE THREAD

**Issue by brenner-company** [appuniversum/ember-appuniversum#346]
Request is regarding a [PR](https://github.com/lblod/ember-rdfa-editor/pull/479) within `@lblod/ember-rdfa-editor` for the addition of two new text styling buttons within the editor toolbar: sub- & superscript.

To facilitate this, we need two new icons: subscript & superscript.

Is this something that can be added to the current set? If yes, can I help with that? And if that is also ok, what is the original source of the current icons?

**Comment by Dietr** [comment]
I try to use the icons from webuniversum. In this case there are none available so will draw some myself. Icons that indicate text style are typically drawn based on the flanders serif font.
