### ISSUE TITLE
[Docs]: AuControlCheckbox is incorrectly named in docs

### ISSUE THREAD

**Issue by abeforgit** [appuniversum/ember-appuniversum#365]
The component's name is AuControlCheckbox, but it's labeled as AuCheckbox in the docs (under `components/forms`)

**Comment by Windvis** [comment]
Good catch. 

Unrelated to the docs issue: I wonder if we should actually rename it to `AuCheckbox` (and `AuRadio`). I'm not sure why the `Control` prefix was used. The Webuniversum equivalents are [vl-ui-checkbox](https://overheid.vlaanderen.be/webuniversum/v3/documentation/forms/vl-ui-checkbox) and [vl-ui-radio](https://overheid.vlaanderen.be/webuniversum/v3/documentation/forms/vl-ui-radio) so it didn't originate there. 🤔
