### ISSUE TITLE
Checkbox component

### ISSUE THREAD

**Issue by Dietr** [appuniversum/ember-appuniversum#37]
We have a component called AuControlCheckbox that is currently in a draft status. We would need to finish this component, the following things are missing:

- The ability to check and uncheck the checkbox and keep the status tracked with an external function
- Test the component and verify it works correctly

**Comment by Dietr** [comment]
After testing on Gelinkt Notuleren it seems that this component (AuControlCheckbox) needs to be reviewed together with the (AuControlRadio). Currently the `@checked` argument does not function correctly and it is also unclear if/how we need to use the `{{ on 'change' }} action.

**Comment by aatauil** [comment]
#83
