### ISSUE TITLE
Addition of various functionality for the toggle-switch component

### ISSUE THREAD

**Issue by brenner-company** [appuniversum/ember-appuniversum#385]
Within Kaleidos we could use the following functionality for the `AuToggleSwitch` component:
- The correct visualisation of the component if there is no label defined (this issue has already been fixed for `AuControlCheckbox` and `AuControlRadio`).
- The possibility of defining a certain alignment for the label (E.g. showing the label on the left of the actual toggle-switch).
- The possibility of defining a loading state for the component (similar to `AuButton`).

Together with some general adjustments:
-  Quick refactor from margin-based spacing to `gap` (already within a few other components).

Is this something that can be added to the component? If yes, I can surely help with that.

**Comment by brenner-company** [comment]
Example of the loading state functionality, currently implemented within Kaleidos:

![CleanShot 2023-03-06 at 15 50 03](https://user-images.githubusercontent.com/18174827/223145780-59dbe299-65b3-44c6-a385-0210ca570e52.gif)

**Comment by Windvis** [comment]
👍 for most of the bullets, but I'm not sure I'm a fan of adding a loading state here. That seems like a very niche use-case since usually switching the toggle doesn't start an async action.

I think it might be better to support something like this instead?

```hbs
<AuToggleSwitch>
  {{#if this.isRunning}}
    <AuLoader />
  {{else}}
    Te handtekenen
  {{/if}}
</AuToggleSwitch>
```
 (Pseudocode, but you get the idea)
