### ISSUE TITLE
AuDropdown in header hidden by data table

### ISSUE THREAD

**Issue by claire-lovisa** [appuniversum/ember-appuniversum#386]
**Describe the bug**

When the `AuDropdown` component in used in a header, it doesn't show in front of the rest of the content on all cases. As you can see in the screenshots below, on a regular page the dropdown shows as expected, but when there is a data table it then

**To Reproduce**

The code is currently not deployed but you can run this PR (minus the css trick) against the dev worship organizations application via `ember serve --proxy https://dev.organisaties.lokaalbestuur.lblod.info`, mock-log in as `Gemeente Aalst` and click on the `Bestuurseenheden` module to find the page with the table.

**Expected behavior**

The dropdown shows in front on the table and is not hidden by it.

**Screenshots**

Hidden dropdown:
![image](https://user-images.githubusercontent.com/23281659/223494201-4acce3dc-3017-4c15-8ed4-16fd890382a1.png)

How I would expect it to show:
![image](https://user-images.githubusercontent.com/23281659/223494637-a8500f0e-eedc-4cb5-84f7-e39fdfe3f544.png)

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser Firefox
- Version 110.0.1

**Comment by Windvis** [comment]
I wonder if this is still an issue with the "floating-ui" based dropdowns. We'll need to try and reproduce the issue.
