### ISSUE TITLE
Provide an option to hide the calendar icon in AuDateInput

### ISSUE THREAD

**Issue by nbittich** [appuniversum/ember-appuniversum#392]
An end user thought that clicking the calendar icon would activate the date picker. Personally, I really like the use of icons, but I understand why some users might expect a date picker functionality.

![image](https://user-images.githubusercontent.com/3816305/226835306-4f872d4f-2c21-481a-9770-a13a3a979db5.png)

**Comment by Windvis** [comment]
Once #429 is merged we can in theory use it inside the `AuDateInput` component as well. It will then  be a simple wrapper around `AuInput` with a [custom date modifier](https://github.com/appuniversum/ember-appuniversum/blob/226d25382705250fc1362517b6b9bbbf62e8403e/addon/components/au-date-input.js#L38-L107) applied. I wonder if we should make that modifier public so you can use it in apps.

```hbs
<AuInput {{au-date-input value=this.value prefillYear=true onChange=this.handleChange}} />
```

That way we don't need to add new arguments to the component, while apps can still style the input the way they want. We could then even deprecate the component and only provide the modifier.

**Comment by nbittich** [comment]
@claire-lovisa fyi

**Comment by claire-lovisa** [comment]
Indeed feels like it would make sense to set the modifier as public !
