### ISSUE TITLE
Addition of action button within toaster alert

### ISSUE THREAD

**Issue by brenner-company** [appuniversum/ember-appuniversum#397]
Within Kaleidos we would love to replace our current & legacy toaster (service) with the one provided within `ember-appuniversum`, but at the moment we're missing the option to add an action button to the bottom of the toaster alert (see quick mockup below).

<img width="324" alt="CleanShot 2023-06-09 at 18 07 48@2x" src="https://github.com/appuniversum/ember-appuniversum/assets/18174827/307a694d-0a5e-4855-90cc-b31c61768a37">

Is this something that can be added to the current toaster component? If yes, can I help with that?

**Comment by brenner-company** [comment]
> I guess we could go for flexibility and allow users to pass in the alert component that needs to be rendered, similar to ember-promise-modals? https://github.com/mainmatter/ember-promise-modals

@Windvis I'm not entirely sure how this should be done/structured? Can you perhaps reference a example within `ember-promise-modals`? Much Thanks!

**Comment by Windvis** [comment]
In ember-promise-modals you have to tell the addon which component it should use, for example: https://github.com/mainmatter/ember-promise-modals#embroider-optimized-apps

`this.modals.open(ConfirmationModal);`

We could do something similar to give users complete control over the rendered toast. Some pseudo-example:

`this.toaster.show(SomeToastComponentWithAButton, options);`

Anyway, I'm not saying we have to go this route. It depends on how flexible we want this to be I guess.

I'm not sure what you had in mind yourself but adding a button with an icon requires quite a bit of extra options if you want everything configurable.

```js
this.toaster.notify('message', 'Notify', {
  // other toast options
  // ..
  actionIcon: 'reload', 
  actionSkin: 'link', 
  actionText: 'Lorem ipsum', 
  actionHandler: someFunction,
  // possibly more options
});
```

In the custom component version most of these options would be part of the component itself, so less things need to be passed in through the options object. And we wouldn't have to make changes here if something extra is needed in the component.
