### ISSUE TITLE
Incorrect flanders-sans font baseline on Windows environments

### ISSUE THREAD

**Issue by brenner-company** [appuniversum/ember-appuniversum#398]
When viewing the Storybook component/styleguide on a Windows environment, in my case Windows 10 with various browsers, the loaded `flanders-sans` font is displayed with a incorrect font baseline in certain situations (font-size, font-weight, etc).

The screenshot below is taken from the `Typography` page ([reference link](https://appuniversum.github.io/ember-appuniversum/?path=/story/utilities-typography--page)) on a Windows 10 machine with Chrome:

![2023-06-09 18_51_42-Utilities _ Typography - Page ⋅ Storybook](https://github.com/appuniversum/ember-appuniversum/assets/18174827/bde1cdc3-65e0-4f83-a90c-6bfdd629cfd0)

FYI: We encountered this issue before within Kaleidos (in more detail, our own CSS package `au-kaleidos-css`) and found a fix. When we replaced the font files with the ones used on https://www.vlaanderen.be/, the issue disappeared. The exact cause of this particular issue was not found (must be linked most likely to the font generator process).

Is there a way to replace the existing font files on the cloudfront cdn that `ember-appuniversum` uses or upload a different (correct) set?

**Comment by Windvis** [comment]
I know nothing about the CDN setup, sorry. Maybe we can bundle the fonts with Appuniversum?

**Comment by brenner-company** [comment]
> I know nothing about the CDN setup, sorry. Maybe we can bundle the fonts with Appuniversum?

I think that is the only possible way. I made a draft PR for you to give it look at https://github.com/appuniversum/ember-appuniversum/pull/399. Thanks!
