### ISSUE TITLE
Ember-power-select issue when place in a scrollable container.

### ISSUE THREAD

**Issue by Dietr** [appuniversum/ember-appuniversum#41]
I did some tests on this. It seems like an issue with the ember-power-select and the scroll containers we are using in ember-appuniversum. The offset of the dropdown is equal to the scrollbar on the au-c-main-container--scroll element (which has overflow:auto to display scrollbars when needed). As soon as you start typing in the power-select search field the position is fixed. I have no solution yet but will create a new issue for this.

_Originally posted by @Dietr in https://github.com/appuniversum/ember-appuniversum/pull/40#issuecomment-693445056_

**Comment by aatauil** [comment]
I see, have you taken into consideration that when removing display:flex from au-c-main-header__title-group also resolves the issue ? The element having that class exists much higher in the dom tree so I don't immediately see how that could have an impact on the c-main-container--scroll that is nested quite some levels deeper in the tree. I could be completely off though but I just want to give you a heads up on that as it pretty weird behavior from my experience.

**Comment by aatauil** [comment]
I see, have you taken into consideration that when removing display:flex from au-c-main-header__title-group also resolves the issue ? The element having that class exists much higher in the dom tree so that makes me think that the issue could possibly not be  specifically the scrollbar on the au-c-main-container--scroll element

**Comment by Dietr** [comment]
So, did some further testing and I have found a possible explanation:
- remove flex from `au-c-main-header__title-group` forces scrollbars on the body element which fixes the dropdown but that's only because the offset of the scrollbars is then corrected
- on other projects we don't have this issue so I guess it's something specific to the placement on mandatendatabank. On other applications we mostly have a sidebar present or another nested scrolling div.
- there's also a possibility that the old webuniversum css files cause this. A bit of a hassle to inspect/fix this.

### Proposed temporary fix:
Adding `overflow: hidden` on the body tag fixes the issue on mandatendatabank so I will add that as a temporary fix in the `_shame.scss` there.

I am not sure how to create a definite fix for this without reviewing the entire main container and scroll behaviour on all the apps. For now, I will monitor the ember-power-select behaviour on the other applications and reopen this issue when needed.
