### ISSUE TITLE
AuBrand duplicate id when using both AuMainHeader & AuMainFooter

### ISSUE THREAD

**Issue by aatauil** [appuniversum/ember-appuniversum#42]
The AuMainHeader & AuMainFooter both use AuBrand that has the id's leeuw and logoVlaanderen. By using both on the same page you get duplicate id's.

**Comment by aatauil** [comment]
Possible solution could be to not make AuMainHeader & AuMainFooter be dependend on AuBrand making them self contained components. Another could be to give the option to pass id's to AuMainHeader & AuMainFooter that would then bubble up to be used by AuBrand

**Comment by Dietr** [comment]
Thanks, this is indeed an issue. Fixed it by adding a generated ember ID using guidFor. So now the brand id's are always prefixed by a unique id.
