### ISSUE TITLE
Showing toaster messages coming from a RDF-form component

### ISSUE THREAD

**Issue by JonasVanHoof** [appuniversum/ember-appuniversum#450]
**Describe the bug**
When rendering a `RDF-form` and displaying certain components in it that are showing toaster messages is not working. The toaster message will show up on the screen but it will never dissapear even if you have set a timeout. Also an error is thrown in the console.

**To Reproduce**

1. Add the toaster service to your component you want to show a message
2. Create the message
3. Check out the message when it is thrown

**Expected behavior**
Should show a toaster message that disappears when the time has passed without throwing an error

**Screenshots**
![image](https://github.com/appuniversum/ember-appuniversum/assets/36266973/80c27cd1-0879-4fca-a7a8-20c6df8fd6f4)

- OS: `Manjaro Gnome 45.1`
- Browser `Brave`

**Comment by JonasVanHoof** [comment]
@Windvis here is the requested bug issue that I encoutered and questioned in [RC](https://chat.semte.ch/group/ember?msg=kqFSiEaxMeKErHqQd)

**Comment by Windvis** [comment]
Closing this since I don't think it's an Appuniversum issue when I look at the error message. I've seen similar issues in the forms due to the way things are rendered there. We can reopen if we run into it again and it does point at Appuniversum.
