### ISSUE TITLE
Use of native `input` element in `au-toggle-switch` component

### ISSUE THREAD

**Issue by elpoelma** [appuniversum/ember-appuniversum#451]
**Is your feature request related to a problem? Please describe the use case and problem it solves.**

Currently, the `au-toggle-switch` component still uses the custom ember `Input` element which promotes two-way-binding. 
It is not possible to pass the `checked` attribute to the `Input` element, only the `@checked` attribute. 

**Describe the solution you'd like**

If the `@checked` attribute is not passed to the `au-toggle-switch` component, it could be a solution to use the native `input` element instead, just as how `au-input` implements it. This would allow users of this library to pass all allowed attributes of an `input` element, including the native `checked` input-attribute.

**Which project(s) or feature(s) is this related to**

We required the use of the native `input` element in a plugin for the editor. For now, we implemented a custom toggle-switch component: https://github.com/lblod/ember-rdfa-editor/blob/ebd8b2eb6a70a010e8130a553e6bb09d55650d22/tests/dummy/app/templates/space-invisible.hbs.

**Comment by Windvis** [comment]
Released as part of [v3.0.0](https://github.com/appuniversum/ember-appuniversum/releases/tag/v3.0.0) 👍
