### ISSUE TITLE
Reference error 'navigator' not found when running with Ember Fastboot

### ISSUE THREAD

**Issue by erikap** [appuniversum/ember-appuniversum#462]
**Describe the bug**
When running an Ember app with Fastboot with ember-appuniversum as a dependency it yields an error like

```
There was an error running your app in fastboot. More info about the error: 
 ReferenceError: navigator is not defined
```

Cause is the `inputmask` dependency. See also https://github.com/RobinHerbots/Inputmask/pull/2704.

Tried to bump the dependency starting from the v2.18 tag in https://github.com/appuniversum/ember-appuniversum/tree/bugfix/upgrade-inputmask but GH doesn't allow creating a PR for a tag.

**To Reproduce**

1. Create  an Ember app with Fastboot
2. Install ember-appuniversum as a dependency
3. Use any component from the library in your app
4. Start the app using `ember serve`
5. When visiting the page in your app, the error will be thrown in the terminal

**Expected behavior**
App should work when running with Fastboot as well.

**Comment by Windvis** [comment]
@erikap I'm not the biggest fan of depending on beta versions in an npm package, but it seems the last stable release has been a while, so maybe we should here..

Would it be a huge problem if we don't release this for the Appuniversum v2? Apps can easily work around this with an override, so I don't think it's really needed to backport this.
