### ISSUE TITLE
Implement a way to clean up unused CSS

### ISSUE THREAD

**Issue by lagartoverde** [appuniversum/ember-appuniversum#48]
We were thinking about implementing a tool like PurgeCSS for cleaning up unused css, but we lack experience with any of these tools.

We mainly want to be very careful on keeping css that is used only in js files.

If anyone could implement one of this tools and test it we would be grateful :)

**Comment by Windvis** [comment]
This is more of a documentation thing I assume? Explain to the end user how something like `purgecss` can be configured properly in Ember apps? Or is it about cleaning up the generated css in the dummy application?

**Comment by aatauil** [comment]
related to this https://chat.semte.ch/group/lblod-all?msg=eAF4NknLMBnpMqqye

**Comment by Dietr** [comment]
I agree that this is something to be done in an application. Will close this issue for now.
