### ISSUE TITLE
`babel-plugin-ember-template-compilation` v2.2.2 incompatibilities

### ISSUE THREAD

**Issue by Windvis** [appuniversum/ember-appuniversum#491]
https://github.com/emberjs/babel-plugin-ember-template-compilation/releases/tag/v2.2.2 includes some fixes for bugs we might actually be depending on by accident.

The error message looks like this: `could not find module ember-template-compiler`

A quick workaround is to pin `babel-plugin-ember-template-compilation` to v2.2.1 using overrides until we can debug and fix the issue here.

```json
  "overrides": {
    "babel-plugin-ember-template-compilation": "2.2.1"
  },
```

Related issue: https://github.com/emberjs/babel-plugin-ember-template-compilation/issues/36

**Comment by Windvis** [comment]
It seems we need to update to ember-template-imports v4 to fix this issue. Hopefully all the v4 issues are resolved..

**Comment by NullVoxPopuli** [comment]
I'd skip all the way to 2.2.5, if you can. lots of bugfixes
