### ISSUE TITLE
AuLoader component sizing options

### ISSUE THREAD

**Issue by Windvis** [appuniversum/ember-appuniversum#65]
It seems the `@size` argument only changes the white-space around the loader animation, is that intended?

https://appuniversum.github.io/ember-appuniversum/docs/atoms/au-loader

**Comment by Windvis** [comment]
It looks like it's intended, it seems to be used to align with other items on the page. Maybe `@whitespace="large"` would be more clear?

I assumed the loader itself would scale, based on that `@size` name :smile:.

**Comment by Windvis** [comment]
Or just drop the `@size` argument altogether and use some of the Appuniversum css classes when needed?

**Comment by Dietr** [comment]
`@whitespace` or `@padding` is indeed a more logical naming for this.
