### ISSUE TITLE
Replace ember-cli-release

### ISSUE THREAD

**Issue by Windvis** [appuniversum/ember-appuniversum#81]
[ember-cli-release](https://github.com/shipshapecode/ember-cli-release#ember-cli-release) is deprecated and it's recommened to switch to [release-it](https://github.com/release-it/release-it#release-it-) instead. This would have the benefit of having access to auto generated changelogs :tada:.

Another downside of ember-cli-release is that it brings in an old graceful-fs version as a transitive dependency which can cause [weird npm errors](https://github.com/release-it/release-it#release-it-) (when primordials is undefined).

**Comment by nvdk** [comment]
:eyes: following as it's probably relevant for our other addons as well

**Comment by Windvis** [comment]
I tried this out in an addon and it's super easy to setup with [create-rwjblue-release-it-setup](https://github.com/rwjblue/create-rwjblue-release-it-setup). It's not something I can do / test myself though, since it requires write access to the repo :smile:.

**Comment by Dietr** [comment]
I replaced ember-cli-release by release-it. I had a look at the more advanced setup but could use some help with setting that up.
