### ISSUE TITLE
Support all LinkTo arguments on the LinkTo wrapper components

### ISSUE THREAD

**Issue by Windvis** [appuniversum/ember-appuniversum#88]
`<AuNavigationLink>` and `<AuLink>` don't support all routing related arguments that LinkTo supports, which means that you sometimes have to use a LinkTo and add the css classes yourselves if you want to target a specific route.

Missing arguments for `<AuLink>`
- ~~`@models`~~
- `@query`

Missing arguments for `<AuNavigationLink>`
- ~~`@model`~~
- ~~`@models`~~
- `@query`

**Comment by Windvis** [comment]
I also think it would be better to rename the `@linkRoute` argument to `@route` since that's what `<LinkTo>` uses and most people will try to use if they don't check the docs. I think aliasing and deprecating `@linkRoute` is the way to go, so apps aren't forced to update everything when they want to update ember-appuniversum.

**Comment by abeforgit** [comment]
I see this has been merged into dev, any chance we can get this into GN asap?
